/**
 * Copyright 2024-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
const fs = require('fs');
const path = require('path');
const prettier = require('prettier');

// Source and destination directories
const parentDir = './types';
const sourceDir = './types/model';
const destDir = './types/processed';
const destDirEnums = './types/processed/enums';
const indexPath = path.join(destDir, 'index.ts');
const internalIndexPath = path.join(destDir, 'internal.ts');
const enumIndexPath = path.join(destDirEnums, 'index.ts');

const filePathReplacements = {
  api: '',
  coinbaseAccount: '',
  accountHold: '',
  accountLedger: '',
  Enum: '',
  ReportCreateResultReportStatus: 'ReportsStatus',
};

const skipFiles = [
  'googleProtobufAny.ts',
  'googleRpcStatus.ts',
  'protobufNullValue.ts',
];

// Replace specific strings
const replacements = {
  '<any>': '',
  "\nimport { RequestFile } from './models';\n": '',
  'static discriminator: string | undefined = undefined;\n\n': '',
  Api: '',
  api: '',
  accountHold: '',
  accountLedger: '',
  coinbaseAccount: '',
  CoinbaseAccountCoinbaseAccount: 'CoinbaseAccount',
  Enum: '',
  AccountLedgerEntryAccountLedgerType: 'EntryAccountLedgerType',
  ReportCreateResultReportStatus: 'ReportsStatus',
  'AddressBookNewAddress.': '', // Edge case for the AddressBookNewAddress namespace
};

const classnameAsExceptions = ['CustodyActivityType', 'PrimeActivityType'];

const prettierConfig = {
  semi: true,
  singleQuote: true,
  trailingComma: 'es5',
  parser: 'typescript',
};

// Ensure the destination directory exists
if (!fs.existsSync(parentDir)) {
  fs.mkdirSync(parentDir, { recursive: true });
}

if (!fs.existsSync(destDir)) {
  fs.mkdirSync(destDir, { recursive: true });
} else {
  fs.rmSync(destDir, { recursive: true });
}

if (!fs.existsSync(destDirEnums)) {
  fs.mkdirSync(destDirEnums, { recursive: true });
}

// Function to replace specific strings
function replaceString(content, replacements) {
  let updatedContent = content;
  for (const [search, replace] of Object.entries(replacements)) {
    updatedContent = updatedContent.split(search).join(replace);
  }
  return updatedContent;
}

function cleanClasses(updatedContent) {
  updatedContent = updatedContent.replace(
    /export class (\w+) \{/g,
    (match, className) => {
      return `export type ${className} = {`;
    }
  );
  // Regular expression to match the function definition and body:
  // - Handles modifiers (async, public, private, etc.)
  // - Matches the function name and parameters
  // - Captures the entire function body, including the curly braces
  let functionName = 'attributeTypeMap';
  let regex = new RegExp(
    `\\s*(?:async|public|private|protected|static|\\s)*${functionName}\\s*(?:<.*?>)?\\s*\\(.*?\\)\\s*(?::\\s*[^=\\{]+)?\\s*\\{[\\s\\S]*?\\}|` + // Matches function definitions
      `\\s*static\\s+${functionName}\\s*:\\s*[^=]+=\\s*\\[[\\s\\S]*?\\];`,
    'g'
  );

  // Remove the function calls from the content
  updatedContent = updatedContent.replace(regex, '');

  functionName = 'getAttributeTypeMap';
  regex = new RegExp(
    `\\s*(?:async|public|private|protected|static|\\s)*${functionName}\\s*(?:<.*?>)?\\s*\\(.*?\\)\\s*(?::\\s*[^=\\{]+)?\\s*\\{[\\s\\S]*?\\}|` + // Matches function definitions
      `\\s*static\\s+${functionName}\\s*:\\s*[^=]+=\\s*\\[[\\s\\S]*?\\];`,
    'g'
  );

  // Remove the function calls from the content
  updatedContent = updatedContent.replace(regex, '');

  regex = /^\s*export\s+namespace\s+\w+\s*\{\s*\}/gm;

  // Remove lines containing namespace
  updatedContent = updatedContent.replace(regex, '');

  // Regex to match `= <value>` where value is a string, number, or boolean
  // Removes default values from the class properties
  // e.g. 'startDate'?: string = '30 days ago from end_date';
  // => 'startDate'?: string;
  updatedContent = updatedContent.replace(
    /=\s*(?:'.*?'|".*?"|\d+(?:\.\d+)?|true|false)/g,
    ''
  );

  return updatedContent;
}

function addGeneratedHeader(updatedContent) {
  const header = `/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 *  Do not edit the class manually.
 */
 `;
  return header + updatedContent;
}

function getTypeName(content, fileName) {
  const typeMatch = content.match(/export\s+type\s+(\w+)\s*=/);
  if (!typeMatch) {
    console.error('No type name found in file: ', fileName);
    throw new Error(`No type name found in file: ${fileName}`);
  }

  return typeMatch[1];
}

function getEnumName(content, fileName) {
  const enumMatch = content.match(/export\s+enum\s+(\w+)\s*/);
  if (!enumMatch) {
    console.error('No enum name found in file: ', fileName);
    throw new Error(`No enum name found in file: ${fileName}`);
  }
  return enumMatch[1];
}

function getIndexFileExport(destPath, updatedContent) {
  const fileName = destPath
    .replace('types/processed/', '')
    .replace('types/processed/enums/', '')
    .replace('.ts', '');

  const isEnum = destPath.includes('enum');
  const baseName = fileName.replace('enums/', '');

  if (isEnum) {
    let typeName = getEnumName(updatedContent, fileName);

    // handle export with as syntax for namespace collisions
    if (classnameAsExceptions.includes(baseName)) {
      typeName = `${typeName} as ${baseName}`;
    }

    return `export { ${typeName} } from './${baseName}';`;
  } else {
    return `export type { ${getTypeName(updatedContent, fileName)} } from './${baseName}';`;
  }
}

async function finalizeAndWriteFile(destPath, updatedContent) {
  updatedContent = addGeneratedHeader(updatedContent);

  console.log('formatting file', destPath);
  updatedContent = await prettier.format(updatedContent, prettierConfig);

  if (fs.existsSync(destPath)) {
    console.log('file already exists: ', destPath);
  }

  // Write the updated content to the destination directory
  fs.writeFileSync(destPath, updatedContent, 'utf8');
}

async function matchImportsAndClass(updatedContent) {
  const importsAndClasses = updatedContent.match(
    /(import\s+[\s\S]+?;|export\s+type\s+\w+\s*=\s*\{[\s\S]*?\})/gm
  );
  return importsAndClasses;
}

async function matchEnums(updatedContent) {
  const enumMatches = [
    ...updatedContent.matchAll(
      /(export\s+(?:namespace\s+\w+\s*\{\s*)?enum\s+\w+\s*\{[\s\S]*?\})\s*\}?/gm
    ),
  ].map((match) => match[1]);
  return enumMatches;
}

function removeOpenApiHeader(updatedContent) {
  const regex = /\/\*[\s\S]*?\*\//;
  return updatedContent.replace(regex, '');
}

function updateImportPaths(enumClasses, updatedContent) {
  // Regular expression to match specific import statements
  const regex = /import\s+\{[^}]+\}\s+from\s+'\.\/(.*?)';/g;

  // Replace the import paths with the updated path
  return updatedContent.replace(regex, (match, importPath) => {
    if (enumClasses.includes(importPath)) {
      return `import { ${match
        .split('{')[1]
        .split('}')[0]
        .trim()} } from './enums/${importPath}';`;
    } else {
      return `import { ${match
        .split('{')[1]
        .split('}')[0]
        .trim()} } from './${importPath}';`;
    }
  });
}

// Main function to process files
async function processFiles() {
  // List all files in the source directory
  const files = fs.readdirSync(sourceDir);
  const indexFileContent = [];
  const internalIndexFileContent = [];
  const enumIndexFileContent = [];

  const enumClasses = [];
  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const sourcePath = path.join(sourceDir, file);
    if (fs.statSync(sourcePath).isFile()) {
      const content = fs.readFileSync(sourcePath, 'utf8');
      const isEnum =
        content.indexOf('export enum') > 0 &&
        content.indexOf('export class') < 0;
      if (isEnum) {
        const filePath = replaceString(
          path.join(destDirEnums, file),
          filePathReplacements
        );
        const enumName = filePath
          .replace('types/processed/enums/', '')
          .replace('.ts', '');
        console.log('processed enum', enumName, filePath);
        enumClasses.push(enumName);
      }
    }
  }

  for (let j = 0; j < files.length; j++) {
    const file = files[j];
    const sourcePath = path.join(sourceDir, file);
    let destPath = path.join(destDir, file);

    if (skipFiles.includes(file)) {
      console.log('skipping file', file);
      continue;
    }

    // Read each file (synchronously or asynchronously)
    if (fs.statSync(sourcePath).isFile()) {
      const content = fs.readFileSync(sourcePath, 'utf8');
      const isEnum = content.indexOf('export enum') > 0;
      const isClass = content.indexOf('export class') > 0;

      let updatedContent = replaceString(content, replacements);

      if (updatedContent.indexOf('class') > 0) {
        updatedContent = cleanClasses(updatedContent);
      }

      updatedContent = removeOpenApiHeader(updatedContent);

      updatedContent = updateImportPaths(enumClasses, updatedContent);

      if (isEnum && isClass) {
        const classFiles = await matchImportsAndClass(updatedContent);
        const className = getTypeName(updatedContent);
        const classFileName = path.join(destDir, className) + '.ts';
        if (destPath.includes('Request') || destPath.includes('Response')) {
          internalIndexFileContent.push(
            getIndexFileExport(classFileName, classFiles[classFiles.length - 1])
          );
        } else {
          indexFileContent.push(
            getIndexFileExport(classFileName, classFiles[classFiles.length - 1])
          );
        }

        const enumFiles = await matchEnums(updatedContent);
        const enumNameMatch = updatedContent.match(
          /export\s+enum\s+(\w+)\s*\{/
        );
        const enumName = enumNameMatch ? enumNameMatch[1] : null;
        const enumFileName = path.join(destDirEnums, enumName) + '.ts';
        enumIndexFileContent.push(
          getIndexFileExport(enumFileName, updatedContent)
        );
        await finalizeAndWriteFile(enumFileName, '\n' + enumFiles);

        // Adding the enum to imports
        classFiles.unshift(
          `import { ${enumName} } from './enums/${enumName}';`
        );

        await finalizeAndWriteFile(
          classFileName,
          '\n' + classFiles.join('\n\n')
        );
      } else if (isEnum) {
        destPath = replaceString(
          path.join(destDirEnums, file),
          filePathReplacements
        );
        enumIndexFileContent.push(getIndexFileExport(destPath, updatedContent));
        await finalizeAndWriteFile(destPath, updatedContent);
      } else {
        destPath = replaceString(destPath, filePathReplacements);
        if (destPath.includes('Request') || destPath.includes('Response')) {
          // Skipping adding internal request/response types to index.ts
          internalIndexFileContent.push(
            getIndexFileExport(destPath, updatedContent)
          );
        } else {
          indexFileContent.push(getIndexFileExport(destPath, updatedContent));
        }
        await finalizeAndWriteFile(destPath, updatedContent);
      }

      console.log(`Processed: ${file} at ${destPath}`);
    }
  }

  // Write to index.ts
  fs.writeFileSync(indexPath, indexFileContent.join('\n') + '\n');
  fs.writeFileSync(
    internalIndexPath,
    internalIndexFileContent.join('\n') + '\n'
  );
  fs.writeFileSync(enumIndexPath, enumIndexFileContent.join('\n') + '\n');

  console.log('All files processed.');
}

// Execute the script
processFiles().then(() => {
  console.log('Processing complete.');
});
