/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type BalanceReport = {
  /**
   * Designated date and time of the balance statement. Timezone is always UTC. If this field is empty, a report of the user’s current balance will be generated.
   */
  datetime?: string;
  /**
   * Not applicable if generating report through an API key; only available through report generation via the Exchange user interface (UI).
   */
  groupByProfile?: boolean;
};
