/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type GetAddressBookResponseAddressInfo = {
  id: string;
  address: string;
  destinationTag?: string;
  currency: string;
  label: string;
  addressBookAddedAt: Date;
  /**
   * Flag to indicate if the crypto addresses has previously been digitally signed and verified when added in the Address Book UI tab
   */
  isVerifiedSelfHostedWallet?: boolean;
  /**
   * The VASP identifier if the address is owned by one of the supported Virtual Asset Service Providers
   */
  vaspId?: string;
  /**
   * Business name of the originator\'s account - only populated for travel rules regions
   */
  businessName?: string;
  /**
   * The country code (ISO 3166-1 alpha-2) of the originator\'s account location - only populated for travel rules regions
   */
  businessCountryCode?: string;
};
