/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { OrderFillLiquidity } from './enums/OrderFillLiquidity';
import { OrderSide } from './enums/OrderSide';

export type OrderFill = {
  /**
   * id of trade that created the fill
   */
  tradeId: number;
  /**
   * book the order was placed on
   */
  productId: string;
  /**
   * uuid
   */
  orderId: string;
  /**
   * id of user\'s account
   */
  userId: string;
  /**
   * profile_id that placed the order
   */
  profileId: string;
  liquidity: OrderFillLiquidity;
  /**
   * price per unit of base currency
   */
  price: string;
  /**
   * amount of base currency to buy/sell
   */
  size: string;
  /**
   * fees paid on current filled amount
   */
  fee: string;
  /**
   * timestamp of fill
   */
  createdAt: Date;
  side: OrderSide;
  /**
   * true if funds have been exchanged and settled
   */
  settled: boolean;
  /**
   * true if funds have been exchanged and settled
   */
  usdVolume: string;
  /**
   * market type which the order was filled in
   */
  marketType?: string;
  /**
   * funding currency which the order was filled in
   */
  fundingCurrency: string;
};
