/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { OrderSide } from './enums/OrderSide';
import { OrderStatus } from './enums/OrderStatus';
import { OrderStop } from './enums/OrderStop';
import { OrderTimeInForce } from './enums/OrderTimeInForce';
import { OrderType } from './enums/OrderType';

export type Order = {
  /**
   * uuid
   */
  id: string;
  /**
   * price per unit of base currency
   */
  price?: string;
  /**
   * amount of base currency to buy/sell
   */
  size?: string;
  /**
   * book the order was placed on
   */
  productId: string;
  /**
   * profile_id that placed the order
   */
  profileId?: string;
  side: OrderSide;
  /**
   * amount of quote currency to spend (for market orders)
   */
  funds?: string;
  /**
   * funds with fees
   */
  specifiedFunds?: string;
  type: OrderType;
  timeInForce?: OrderTimeInForce;
  /**
   * timestamp at which order expires
   */
  expireTime?: Date;
  /**
   * if true, forces order to be `maker` only
   */
  postOnly: boolean;
  /**
   * timestamp at which order was placed
   */
  createdAt: Date;
  /**
   * timestamp at which order was done
   */
  doneAt?: Date;
  /**
   * reason order was done (filled, rejected, or otherwise)
   */
  doneReason?: string;
  /**
   * reason order was rejected by engine
   */
  rejectReason?: string;
  /**
   * fees paid on current filled amount
   */
  fillFees: string;
  /**
   * amount (in base currency) of the order that has been filled
   */
  filledSize: string;
  executedValue?: string;
  status: OrderStatus;
  /**
   * true if funds have been exchanged and settled
   */
  settled: boolean;
  stop?: OrderStop;
  /**
   * price (in quote currency) at which to execute the order
   */
  stopPrice?: string;
  fundingAmount?: string;
  /**
   * client order id
   */
  clientOid?: string;
  /**
   * market type where order was traded
   */
  marketType?: string;
  /**
   * maximum visible quantity for iceberg order
   */
  maxFloor?: string;
  /**
   * order id for the visible order for iceberg order
   */
  secondaryOrderId?: string;
  /**
   * stop limit price for TPSL order
   */
  stopLimitPrice?: string;
};
