/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { MonorailLinkedResource } from './MonorailLinkedResource';
import { PaymentMethodAvailableBalance } from './PaymentMethodAvailableBalance';
import { PaymentMethodLimits } from './PaymentMethodLimits';
import { PaymentMethodPickerData } from './PaymentMethodPickerData';
import { PaymentMethodRecurringOption } from './PaymentMethodRecurringOption';

export type PaymentMethod = {
  id: string;
  type: string;
  name: string;
  currency: string;
  primaryBuy: boolean;
  primarySell: boolean;
  instantBuy: boolean;
  instantSell: boolean;
  createdAt: Date;
  updatedAt: Date;
  resource: string;
  resourcePath: string;
  verified?: boolean;
  limits?: PaymentMethodLimits;
  allowBuy?: boolean;
  allowSell?: boolean;
  allowDeposit?: boolean;
  allowWithdraw?: boolean;
  fiatAccount?: MonorailLinkedResource;
  cryptoAccount?: MonorailLinkedResource;
  recurringOptions?: Array<PaymentMethodRecurringOption>;
  availableBalance?: PaymentMethodAvailableBalance;
  pickerData?: PaymentMethodPickerData;
  holdBusinessDays?: number;
  holdDays?: number;
  verificationMethod?: string;
  cdvStatus?: string;
};
