/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { AccountReport } from './AccountReport';
import { BalanceReport } from './BalanceReport';
import { FillsReport } from './FillsReport';
import { OtcFillsReport } from './OtcFillsReport';
import { ReportFormat } from './enums/ReportFormat';
import { RfqFillsReport } from './RfqFillsReport';
import { TaxInvoiceReport } from './TaxInvoiceReport';

export type PostReportsRequest = {
  /**
   * Type of report to generate. Possible values: [`account`, `balance`, `fills`, `otc-fills`, `rfq-fills`, `tax-invoice`, `1099k-transaction-history`]
   */
  type: string;
  /**
   * required for `1099k-transaction-history`-type reports
   */
  year?: string;
  format?: ReportFormat;
  /**
   * Email to send generated report notification to
   */
  email?: string;
  /**
   * If this field is specified, it must be the `profile_id` that is linked to the API key.
   */
  profileId?: string;
  balance?: BalanceReport;
  fills?: FillsReport;
  account?: AccountReport;
  otcFills?: OtcFillsReport;
  taxInvoice?: TaxInvoiceReport;
  rfqFills?: RfqFillsReport;
};
