/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { OrderCancelAfter } from './enums/OrderCancelAfter';
import { OrderSide } from './enums/OrderSide';
import { OrderStop } from './enums/OrderStop';
import { OrderStpFlag } from './enums/OrderStpFlag';
import { OrderTimeInForce } from './enums/OrderTimeInForce';
import { OrderType } from './enums/OrderType';

export type PostOrdersRequest = {
  /**
   * Create order on a specific `profile_id`. If none is passed, defaults to `default` profile.
   */
  profileId?: string;
  type?: OrderType;
  side: OrderSide;
  /**
   * Book on which to place an order
   */
  productId: string;
  stp?: OrderStpFlag;
  stop?: OrderStop;
  /**
   * Price threshold at which a `stop` order will be placed on the book
   */
  stopPrice?: string;
  /**
   * Price per unit of cryptocurrency - required for `limit`/`stop` orders
   */
  price?: string;
  /**
   * Amount of base currency to buy or sell - required for `limit`/`stop` orders and `market` `sell`s
   */
  size?: string;
  /**
   * Amount of quote currency to buy - required for `market` `buy`s
   */
  funds?: string;
  timeInForce?: OrderTimeInForce;
  cancelAfter?: OrderCancelAfter;
  /**
   * If true, order will only execute as a `maker` order
   */
  postOnly?: boolean;
  /**
   * Optional Order ID selected by the user or the frontend client to identify their order
   */
  clientOid?: string;
  /**
   * Placing an iceberg order. Use this to specify how much to show
   */
  maxFloor?: string;
  /**
   * Required for take profit/stop loss orders. Denotes the updated limit price upon the activation of the stop loss trigger
   */
  stopLimitPrice?: string;
};
