/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { ProductStatus } from './enums/ProductStatus';

export type Product = {
  id: string;
  baseCurrency: string;
  quoteCurrency: string;
  /**
   * Min order price (a.k.a. price increment
   */
  quoteIncrement: string;
  baseIncrement: string;
  displayName: string;
  minMarketFunds: string;
  marginEnabled: boolean;
  postOnly: boolean;
  limitOnly: boolean;
  cancelOnly: boolean;
  status: ProductStatus;
  statusMessage: string;
  tradingDisabled?: boolean;
  fxStablecoin?: boolean;
  maxSlippagePercentage?: string;
  auctionMode: boolean;
  /**
   * Percentage to calculate highest price for limit buy order (Stable coin trading pair only)
   */
  highBidLimitPercentage?: string;
};
