/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { TravelRulesData } from './TravelRulesData';

export type PublicPostTransferCryptoRequest = {
  profileId?: string;
  amount: string;
  currency: string;
  cryptoAddress: string;
  destinationTag?: string;
  noDestinationTag?: boolean;
  nonce?: number;
  network?: string;
  /**
   * A boolean flag to add the network fee on top of the amount. If this is blank, it will default to deducting the network fee from the amount.
   */
  addNetworkFeeToTotal?: boolean;
  /**
   * A boolean flag to create a transfer using Coinbase as an intermediary VASP. If `true`, `intermediary_jurisdiction` must be provided. `travel_rule_data` may be necessary if the jurisdiction requires data.
   */
  isIntermediary?: boolean;
  travelRuleData?: TravelRulesData;
};
