/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { Date } from './Date';
import { OriginatingVaspForIntermediary } from './OriginatingVaspForIntermediary';
import { StreetAddress } from './StreetAddress';
import { TravelRulesNaturalName } from './TravelRulesNaturalName';

export type TravelRulesData = {
  /**
   * Required: name of the originator sending the funds
   */
  originatorName?: string;
  originatorNaturalName?: TravelRulesNaturalName;
  originatorAddress?: StreetAddress;
  originatorTelephoneNumber?: string;
  /**
   * An account identifier for the originator.
   */
  originatorAccount?: string;
  /**
   * The country code (ISO 3166-1 alpha-2) of the originator\'s account location.
   */
  originatorAccountLocationCountryCode?: string;
  originatorDateOfBirth?: Date;
  /**
   * Required: account number of the originator sending the funds.
   */
  originatorAccountNumber?: string;
  /**
   * The purpose of the transfer.
   */
  transferPurpose?: string;
  /**
   * Required: name of the beneficiary receiving the funds
   */
  beneficiaryName?: string;
  beneficiaryAddress?: StreetAddress;
  /**
   * The telephone number of the beneficiary.
   */
  beneficiaryTelephoneNumber?: string;
  /**
   * The country code (ISO 3166-1 alpha-2) of the beneficiary\'s account location.
   */
  beneficiaryAccountLocation?: string;
  beneficiaryDateOfBirth?: Date;
  /**
   * The beneficiary financial institution, e.g. Coinbase.
   */
  beneficiaryFinancialInstitution?: string;
  /**
   * Required: whether the user claims the receiving wallet belongs to the originator
   */
  isSelf?: boolean;
  /**
   * The crypto address of the originator.
   */
  originatorWalletAddress?: string;
  originatingVaspForIntermediary?: OriginatingVaspForIntermediary;
};
