/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type WrappedAsset = {
  /**
   * The symbol of the wrapped asset
   */
  id: string;
  /**
   * The assets wrapped by customers less the assets unwrapped by customers existing outside of Coinbase\'s premint account
   */
  circulatingSupply: string;
  /**
   * The total token supply of the asset matching that on Etherscan
   */
  totalSupply: string;
  /**
   * The conversion rate between the wrapped asset and the underlying asset
   */
  conversionRate: string;
  /**
   * The APY earned by the supply of the underlying asset
   */
  apy: string;
  /**
   * The estimated time to redeem the wrapped asset in days
   */
  redeemTimeEstimateDays: string;
};
